language: python
python:
  - "3.6"
env:
- DJANGO_VERSION=1.11.4
install:
- pip install -r requirements.txt
before_script:
- python3 django-basic/manage.py makemigrations
- python3 django-basic/manage.py migrate
script:
- python3 django-basic/manage.py test
