language: python
python:
  - "3.6"
env:
- DJANGO_VERSION=1.11.4
install:
- pip install -r requirements.txt
before_script:
- python3 django-basic/manage.py makemigrations
- python3 django-basic/manage.py migrate
script:
- python3 django-basic/manage.py test
deploy:
  provider: heroku
  api_key:
    secure: b0c94c20-4378-403c-9e67-d3ac2ce41a11
  app: gcs01-vinicinolivera-travis
